### ISSUE TITLE
Credentials Issue Causes Repeated Login Failures

### ISSUE THREAD

**Issue by Geraden07** [wmaop/wm-jbehave#13]
Currently if a user provides incorrect credentials and attempts to run the wm-jbehave unit tests, it attempts to login with these incorrect credentials for each and every test case, causing numerous failed login attempts which can lead to account lockouts.

Ideally, after the first failed connection attempt, all subsequent tests should be aborted to avoid this.

**Comment by sysgen** [comment]
Added System.exit(1) which aborts running of story file however if multiple story files exist, will try once per file.  This reduces the attempts but not perfectly.

**Comment by Geraden07** [comment]
This was my original thought, and I tried it actually be later removed it from my pull request because it wasn't fully addressing the issue.

Might I suggest in the BeforeStories part trying to connect once and if the connection fails, exit before any stories are launched?
