### ISSUE TITLE
Wiki Needs Updating

### ISSUE THREAD

**Issue by Geraden07** [wmaop/wm-jbehave#14]
The settings.xml file on the wm-jbehave Wiki page Using-Maven-to-configure-Designer ( https://github.com/wmaop/wm-jbehave/wiki/Using-Maven-to-configure-Designer ) needs to be updated to point to the new organisation owned bintray repo ( http://dl.bintray.com/wm-aop/maven ).

**Comment by sysgen** [comment]
Fixed.
